---
title: "Urban Growth Modeling in Nashville, Tennessee"
author: "Shengqian Wang and Jack Rummler"
date: "2023-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
#library(QuantPsyc) # JE Note: in R 4.1, QuantPsyc package not available.
library(caret)
library(yardstick)
library(pscl)
library(plotROC) 
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(viridis)
library(igraph)
library(RSocrata)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  panel.border=element_rect(colour="black"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))
```

```{r}
tennessee <- counties("TN")

nashville <- tennessee %>%
  dplyr::filter(NAMELSAD == "Davidson County")%>%
  st_transform('ESRI:103527')
ggplot()+
  geom_sf(data=tennessee, fill='grey', color='black')+
  geom_sf(data=nashville, fill='red', color='black')+
  labs(title="Davidson County, Tennessee")+
  mapTheme
```
```{r}
# create fishnet
Nashville_fishnet <- 
  st_make_grid(nashville, 1000) %>%
  st_sf()

# clip to nashville
Nashville_fishnet <-
  Nashville_fishnet[nashville,]
# plot
ggplot() +
  geom_sf(data=Nashville_fishnet) +
  labs(title="Fishnet, 4000 Foot Resolution") +
  mapTheme
```


```{r}
## install.packages("RSocrata")




##  Metropolitan Transit Authority Bus Routes and remove null
bus_stop <- read.socrata(
  "https://data.nashville.gov/resource/vfe9-k7vc.json",
  app_token = "j9XHS8weUKChc4dFGzE03GdIU",
  email     = "ltscqian@gmail.com",
  password  = "qifx!7UR2m4GG8T"
) %>%
  na.omit(bus_stop, cols = "geocoded_column.latitude")



# convert bus_stop to sf
bus_stop_sf <- bus_stop %>%
    st_as_sf(coords = c("geocoded_column.longitude", "geocoded_column.latitude"), crs = 4326) %>%
    st_transform(st_crs(nashville)) %>%
    st_intersection(nashville)

#plot 
ggplot()+
  geom_sf(data=nashville, fill='white', color='black')+
  geom_sf(data=bus_stop_sf,color='purple')+
  labs(title="Davidson County, Tennessee")+
  mapTheme
##  bus_route_sf <- bus_route %>%
##    st_as_sf(wkt = "the_geom.corrdiantes", crs = 4326)

```

